### PR TITLE
Advance config options for port channels

### PR DESCRIPTION
**Pull request by vivek-metricdust**
ui config functionality for [#52](https://github.com/STORDIS/orca_nw_lib/issues/52)

- additional config for portchannel added

1.   for static”
2. fallback 
3. fast-rate 
4. min-links
5. description 
6. graceful_shutdown_mode

- vlan member management added i,e, adding vlans and tagging them with remove all option
- Remove for vlan members only support remove all and individual removal is not suported

### CODE REVIEW

**Comment by kamalkrbh** [comment]
@vivek-metricdust 
image
Not clear what checkbox with "-"  represents.

**Comment by kamalkrbh** [comment]
@vivek-metricdust , PortChannel IP deletion doesn't work. Still teh UI show a success. 
image
image
REesconf Notebook also still shows the IP.

**Comment by kamalkrbh** [comment]
@vivek-metricdust , Similar is the case with description.

**Comment by vivek-metricdust** [comment]
> @vivek-metricdust , Similar is the case with description. Cant delete it.

This is known issue and will be fixed in [#40](https://github.com/STORDIS/orca_backend/issues/40)

**Comment by vivek-metricdust** [comment]
> @vivek-metricdust , PortChannel IP deletion doesn't work. Still teh UI show a success. image image Restconf Notebook also still shows the IP.

This issue is known and will be fixed during [#40](https://github.com/STORDIS/orca_backend/issues/40)

**Pull request merged**
