### PR TITLE
MCLAG Domain- Additional configuration.

### PR DESCRIPTION
**Pull request by vivek-metricdust**
fixes [#63](https://github.com/STORDIS/orca_nw_lib/issues/63)

- added new config option in mclag table
- added check box in table header

### CODE REVIEW

**Comment by kamalkrbh** [comment]
@vivek-metricdust , The new config options should appear in popup while creating MCLAG.

**Comment by kamalkrbh** [comment]
As per @vivek-metricdust, The missing parameters from pop up will be added with the fix of 
[#65](https://github.com/STORDIS/orca_nw_lib/issues/65)

**Review by kamalkrbh — CHANGES_REQUESTED** [review]
@vivek-metricdust,
mclag system mac is an optional field. Infact domain id is the only mandatory field.
Gateway mac configuration is not working.

**Review by kamalkrbh — CHANGES_REQUESTED** [review]
@vivek-metricdust, Also check which fields are editable and deletable after mclag has been created. There should be provision for that.
For that refer restconf (notebook)

**Review by kamalkrbh — CHANGES_REQUESTED** [review]
@vivek-metricdust, domain id can not be zero.

**Comment by vivek-metricdust** [comment]
mentioned changes are done and pushed 

Note - issue is dependent on PR of library and backend
Library PR - [Mclag domain additional configuration. - lib - #63 #75](https://github.com/STORDIS/orca_nw_lib/pull/75)
Backend PR - [Mclag domain additional configuration. - b - #63 STORDIS/orca_backend#47](https://github.com/STORDIS/orca_backend/pull/47)

**Comment by vivek-metricdust** [comment]
> @vivek-metricdust, domain id can not be zero.
> @vivek-metricdust, Also check which fields are editable and deletable after mclag has been created. There should be provision for that. For that refer restconf (notebook)
> @vivek-metricdust, mclag system mac is an optional field. Infact domain id is the only mandatory field. Gateway mac configuration is not working.
> @vivek-metricdust , The new config options should appear in popup while creating MCLAG.

These issues are fixed and branch is up to date

**Pull request merged**
