### PR TITLE
Pressing esc key close the pop up. #144

### LINKED ISSUE #144: Pressing esc key while a pop-up is opened can be considered a command to close the pop up.
While pressing escape key when a pop up is open e.g. "Add Port Channel" should be closed.

### PR DESCRIPTION
**Pull request by vivek-metricdust**
fixes #144 

on pressing esc key the popup models will be closed.

### CODE REVIEW

**Comment by kamalkrbh** [comment]
@vivek-metricdust ,Can we make base functioal component for all the forms, benifit of that would be Inheritance like property in functional compenents. Currently there are lots of common behaviours across various forms like handle submit, handle change, handle key down. And some of those behaviours are exactly same.

If we copy the behaviours in every form (or any other) component, there are high chances of some behavour missed and components will not remain uniform. Like all popup form can be closed by pressing escape but Dicovery form missed.

**Comment by kamalkrbh** [comment]
Getting following error while adding portchannel with out changing or entering any value in the form.
image

**Comment by kamalkrbh** [comment]
@vivek-metricdust , while adding vlan without changing any value in the form :
image

Also I see payload has a lots of empty values - 
image

**Comment by vivek-metricdust** [comment]
@kamalkrbh above mentioned issue are fixed and pushed

**Comment by kamalkrbh** [comment]
Still whle pressing esp on pop up for delete config option (on every tab), I see this - 
image

**Pull request merged**
